# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

safe: true
markdown: kramdown
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : "My mind is mine"
tagline: minescript
keywords: [minescript]
description: minescript的博客，my mind is mine
author :
  name : 徐铭杰
  email : xumingjie1658@163.com
  github : xumingjie1658

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://xumingjie1658.github.io

links:
  - name:         首页
    url:          /
  - name:         About
    url:          /about
  - name:         简书
    url:          http://www.jianshu.com/users/b46aab0781a2/latest_articles
    external:     true
  - name:         GitHub
    url:          http://github.com/xumingjie1658
    external:     true

en:
  links:
    - name:         Home
      url:          /
    - name:         About
      url:          /about
    - name:         JianShu
      url:          http://www.jianshu.com/users/b46aab0781a2/latest_articles
      external:     true
    - name:         GitHub
      url:          http://github.com/xumingjie1658
      external:     true
